Pre-Merge Tests 4

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,9 +27,20 @@ jobs:
             exit 1
           fi
 
-      - name: Fail on Check commits failure
+      # Example: Fail the workflow if tests fail
+      - name: Fail on test failure
         if: failure()
         run: exit 1
+
+      # Update status check
+      - name: Set status check
+        run: |
+          if [ ${{ job.status }} == "success" ]; then
+             echo "Tests passed!"
+          else
+            echo "Tests failed!"
+            exit 1
+          fi
 
 #      # Perform merge if tests pass
 #      - name: Merge to staging
